FROM registry.cn-hangzhou.aliyuncs.com/palan/apache-drill:1.16.0

COPY 3rdparty  /apache-drill-1.16.0/jars/3rdparty
COPY target/drill-java-exec-1.16.0.jar /apache-drill-1.16.0/jars/drill-java-exec-1.16.0.jar
